Wrong trace delay - fix 2035819
TAPAAL/verifydtapn pull request #45
Opened 2024-06-14 00:01 UTC by mtygesen

Fix for:
https://bugs.launchpad.net/tapaal/+bug/2035819

2024-06-16 19:10 UTC, srba commented
One could have set the max constant to 0 already at line 122 with the same effect (at least from a quick look). I am though afraid that this could kill some of the optimizations as if the constant is -1 the engine regards it essentially as untimed place. I think that maybe one could set it to 0 at line 122 only if we ask for the fastest trace, otherwise we could leave it at -1. What do you think @petergjoel ?

2026-05-31 14:45 UTC, mtygesen commented
It looks like PWHybridList when adding markings, and isLiveness = False only saves the first and not the shortest path.

2026-06-12 13:06 UTC, srba requested changes
On the attached example, if you select "no trace" the engine returns an error.
[fastest-trace-error-no-trace.tapn.zip](https://github.com/user-attachments/files/28880258/fastest-trace-error-no-trace.tapn.zip)

2026-07-01 07:30 UTC, srba approved these changes
tested and all looks fine, so merging to main

2026-07-01 07:30 UTC, merged